HISTSIZE=999999
HISTFILESIZE=9999999
SAVEHIST=$HISTSIZE
DISABLE_MAGIC_FUNCTIONS="true"
source $HOME/.dotfiles/zsh/antigenrc
source $HOME/.dotfiles/node/nvmrc
source $HOME/.dotfiles/functions/functions

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export JAVA_HOME="/Users/matt/.sdkman/candidates/java/current"
export CATALINA_HOME="/Users/matt/tools/apache-tomcat-7.0.73"
export ANT_HOME="/usr/local/Cellar/ant/1.9.8/libexec"
export JMETER_HOME="/Users/matt/tools/apache-jmeter-3.1"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/matt/.sdkman"
export PATH="/usr/local/sbin:$PATH"
export PATH="/Users/matt/tools:$PATH"
# Sourcing Aliases
source $HOME/.dotfiles/aliases/gradle
source $HOME/.dotfiles/aliases/ssh
source $HOME/.dotfiles/aliases/tomcat
source $HOME/.dotfiles/aliases/random
source $HOME/.dotfiles/aliases/osx
source $HOME/.dotfiles/aliases/kubectl
source $HOME/.dotfiles/aliases/fishfry

export PATH="/usr/local/opt/openssl/bin:$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/vault vault

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

. /usr/local/etc/profile.d/z.sh

source "$HOME/.sdkman/bin/sdkman-init.sh"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"

#export PATH="$PATH:/Users/matt/tools/istio-1.11.3/bin"
export PATH="$PATH:/Users/matt/tools/istio-1.15.0/bin"

export PATH="$PATH:/Users/matt/tools/kafka_2.13-3.0.0/bin"

# Kubectl shell completion
source <(kubectl completion zsh)


eval $(thefuck --alias)
export PATH="/usr/local/opt/openssl@3/bin:$PATH"

export PATH="/Users/matt/.local/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export EDITOR=vim
autoload -U compinit; compinit
source <(stern --completion=zsh)
export PATH="$PATH:/Users/matt/dev/recoverx/infrastructure/charts/istio/istio-1.18.0/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/matt/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/matt/tools/google-cloud-sdk/path.zsh.inc'; fi

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# The next line enables shell command completion for gcloud.
if [ -f '/Users/matt/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/matt/tools/google-cloud-sdk/completion.zsh.inc'; fi
