source $HOME/.dotfiles/zsh/antigenrc
source $HOME/.dotfiles/node/nvmrc
source $HOME/.dotfiles/functions/functions

export NVM_DIR="${HOME}/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Sourcing Aliases
source $HOME/.dotfiles/aliases/gradle
source $HOME/.dotfiles/aliases/ssh
